# -*- coding: utf-8 -*-
"""
Created on Tue Dec 21 16:23:52 2021

@author: larsh
"""

states = {'Alabama': 'MONTGOMERY',
              'Alaska': 'JUNEAU',
              'Arizona': 'PHOENIX',
              'Arkansas': 'LITTLE ROCK',
              'California': 'SACRAMENTO',
              'Colorado': 'DENVER',
              'Connecticut': 'HARTFORD',
              'Delaware': 'DOVER',
              'Florida': 'TALLAHASSEE',
              'Georgia': 'ATLANTA',
              'Hawaii': 'HONOLULU',
              'Idaho': 'BOISE',
              'Illinois': 'SPRINGFIELD',
              'Indiana': 'INDINAPOLIS',
              'Iowa': 'DES MOINES',
              'Kansas': 'TOPEKA',
              'Kentucky': 'FRANKFORT',
              'Louisiana': 'BATON ROUGE',
              'Maine': 'AUGUSTA',
              'Maryland': 'ANNAPOLIS',
              'Massachusetts': 'BOSTON',
              'Michigan': 'LANSING',
              'Minnesota': 'SAINT PAUL',
              'Mississippi': 'JACKSON',
              'Missouri': 'JEFFERSON CITY',
              'Montana': 'HELENA',
              'Nebraska': 'LINCOLN',
              'Nevada': 'CARSON CITY',
              'New Hampshire': 'CONCORD',
              'New Jersey': 'TRENTON',
              'New Mexico': 'SANTA FE',
              'New York': 'ALBANY',
              'North Carolina': 'RALEIGH',
              'North Dakota': 'BISMARCK',
              'Ohio': 'COLOMBUS',
              'Oklahoma': 'OKLAHOMA CITY',
              'Oregon': 'SALEM',
              'Pennsylvania': 'HARRISBURG',
              'Rhode Island': 'PROVIDENCE',
              'South Carolina': 'COLUMBIA',
              'South Dakota': 'PIERRE',
              'Tennessee': 'NASHVILLE',
              'Texas': 'AUSTIN',
              'Utah': 'SALT LAKE CITY',
              'Vermont': 'MONTPELIER',
              'Virginia': 'RICHMOND',
              'Washington': 'OLYMPIA',
              'West Virginia': 'CHARLESTON',
              'Wisconsin': 'MADISON',
              'Wyoming': 'CHEYENNE'}

countries = {'Afghanistan': 'KABUL',
			 'Aland Islands': 'MARIEHAMN',
			 'Albania': 'TIRANA',
			 'Algeria': 'ALGIERS',
			 'American Samoa': 'PAGO PAGO',
			 'Andorra': 'ANDORRA LA VELLA',
			 'Angola': 'LUANDA',
			 'Anguilla': 'THE VALLEY',
			 'Antigua and Barbuda': 'SAINT JOHNS',
			 'Argentina': 'BUENOS AIRES',
			 'Armenia': 'YEREVAN',
			 'Aruba': 'ORANJESTAD',
			 'Australia': 'CANBERRA',
			 'Austria': 'VIENNA',
			 'Azerbaijan': 'BAKU',
			 'Bahamas': 'NASSAU',
			 'Bahrain': 'MANAMA',
			 'Bangladesh': 'DHAKA',
			 'Barbados': 'BRIDGETOWN',
			 'Belarus': 'MINSK',
			 'Belgium': 'BRUSSELS',
			 'Belize': 'BELMOPAN',
			 'Benin': 'PORTO NOVO',
			 'Bermuda': 'HAMILTON',
			 'Bhutan': 'THIMPHU',
			 'Bolivia': 'LA PAZ',
			 'Bosnia and Herzegovina': 'SARAJEVO',
			 'Botswana': 'GABORONE',
			 'Brazil': 'BRASILIA',
			 'Brunei': 'BANDAR SERI BEGAWAN',
			 'Bulgaria': 'SOFIA',
			 'Burkina Faso': 'OUAGADOUGOU',
			 'Burundi': 'GITEGA',
			 'Cambodia': 'PHNOM PENH',
			 'Cameroon': 'YAOUNDE',
			 'Canada': 'OTTAWA',
			 'Cape Verde': 'PRAIA',
			 'Central African Republic': 'BANGUI',
			 'Chad': 'NDJAMENA',
			 'Chile': 'SANTIAGO',
			 'China': 'BEIJING',
			 'Colombia': 'BOGOTA',
			 'Comoros': 'MORONI',
			 'Republic of the Congo': 'BRAZZAVILLE',
			 'The Democratic Republic of the Congo': 'KINSHASA',
			 'Costa Rica': 'SAN JOSE',
			 'Côte d''Ivoire': 'YAMOUSSOUKRO',
			 'Croatia': 'ZAGREB',
			 'Cuba': 'HAVANNA',
			 'Cyprus': 'NICOSIA',
			 'Czech Republic': 'PRAGUE',
			 'Denmark': 'COPENHAGEN',
			 'Djibouti': 'DJIBOUTI',
			 'Dominica': 'ROSEAU',
			 'Ecuador': 'QUITO',
			 'Egypt': 'CAIRO',
			 'El Salvador': 'SAN SALVADOR',
			 'Equatorial Guinea': 'MALABO',
			 'Eritrea': 'ASMARA',
			 'Estonia': 'TALLINN',
			 'Ethiopia': 'ADDIS ABABA',
			 'Falkland Islands': 'STANLEY',
			 'Fiji': 'SUVA',
			 'Finland': 'HELSINKI',
			 'France': 'PARIS',
			 'French Guiana': 'CAYENNE',
			 'Gabon': 'LIBREVILLE',
			 'Gambia': 'BANJUL',
			 'Gibraltar': 'GIBRALTAR',
			 'Greece': 'ATHENS',
			 'Greenland': 'NUUK',
			 'Grenada': 'SAINT GEORGES',
			 'Guadeloupe': 'BASSE-TERRE',
			 'Guatemala': 'GUATEMALA CITY',
			 'Guinea': 'CONAKRY',
			 'Guinea-Bissau': 'BISSAU',
			 'Guyana': 'GEORGETOWN',
			 'Haiti': 'PORT AU PRINCE',
			 'Honduras': 'TEGUCIGALPA',
			 'Hungary': 'BUDAPEST',
			 'Iceland': 'REYKJAVIK',
			 'India': 'NEW DELHI',
			 'Indonesia': 'JAKARTA',
			 'Iran': 'TEHRAN',
			 'Iraq': 'BAGHDAD',
			 'Ireland': 'DUBLIN',
			 'Israel': 'JERUSALEM',
			 'Italy': 'ROME',
			 'Jamaica': 'KINGSTON',
			 'Japan': 'TOKYO',
			 'Jordan': 'AMMAN',
			 'Kazakhstan': 'ASTANA',
			 'Kenya': 'NAIROBI',
			 'Kiribati': 'TARAWA',
			 'North Korea': 'PYONGYANG',
			 'South Korea': 'SEOUL',
			 'Kuwait': 'KUWAIT CITY',
			 'Kyrgyzstan': 'BISHKEK',
			 'Laos': 'VIENTIANE',
			 'Latvia': 'RIGA',
			 'Lebanon': 'BEIRUT',
			 'Lesotho': 'MASERU',
			 'Liberia': 'MONROVIA',
			 'Libya': 'TRIPOLI',
			 'Liechtenstein': 'VADUZ',
			 'Lithuania': 'VILNIUS',
			 'Luxembourg': 'LUXEMBOURG CITY',
			 'Macedonia' : 'SKOPJE',
			 'Madagascar': 'ANTANANARIVO',
			 'Malawi': 'LILONGWE',
			 'Malaysia': 'KUALA LUMPUR',
			 'Maldives': 'MALE',
			 'Mali': 'BAMAKO',
			 'Malta': 'VALETTA',
			 'Marshall Islands': 'MAJURO',
			 'mauritania': 'NOUAKCHOTT',
			 'Mauritius': 'PORT LOUIS',
			 'Mexico': 'MEXICO CITY',
			 'Micronesia': 'PALIKIR',
			 'Moldova': 'CHISINAU',
			 'Monaco': 'MONTE CARLO',
			 'Mongolia': 'ULAN BATOR',
			 'Montenegro': 'PODGORICA',
			 'Morocco': 'RABAT',
			 'Mozambique': 'MAPUTO',
			 'Myanmar': 'NAYPYIDAW',
			 'Namibia': 'WINDHOEK',
			 'Nauru': 'YAREN',
			 'Nepal': 'KATHMANDU',
			 'Netherlands': 'AMSTERDAM',
			 'New Zealand': 'WELLINGTON',
			 'Nicaragua': 'MANAGUA',
			 'Niger': 'NIAMEY',
			 'Nigeria': 'ABUJA',
			 'Niue': 'ALOFI',
			 'Norway': 'OSLO',
			 'Oman': 'MUSCAT',
			 'Pakistan': 'ISLAMABAD',
			 'Palau': 'NGERULMUD',
			 'Panama': 'PANAMA CITY',
			 'Papua New Guinea': 'PORT MORESBY',
			 'Paraguay': 'ASUNCION',
			 'Peru': 'LIMA',
			 'Phillipines': 'MANILA',
			 'Poland': 'WARSAW',
			 'Portugal': 'LISBON',
			 'Puerto Rico': 'SAN JUAN',
			 'Qatar': 'DOHA',
			 'Romania': 'BUCHAREST',
			 'Russia': 'MOSCOW',
			 'Rwanda': 'KIGALI',
			 'Saint Kitts and Nevis': 'BASSETERRE',
			 'Saint Lucia': 'CASTRIES',
			 'Saint Vincent and the Grenadines': 'KINGSTOWN',
			 'Samoa': 'APIA',
			 'San Marino': 'SAN MARINO',
			 'Sao Tome and Principe': 'SAO TOME',
			 'Saudi Arabia': 'RIYADH',
			 'Senegal': 'DAKAR',
			 'Serbia': 'BELGRADE',
			 'Seychelles': 'VICTORIA',
			 'Sierra Leone': 'FREETOWN',
			 'Singapore': 'SINGAPORE',
			 'Slovakia': 'BRATISLAVA',
			 'Solomon Islands': 'HONIARA',
			 'Somalia': 'MOGADISHU',
			 'South Africa': 'PRETORIA','BLOEMFONTEIN'
			 'Spain': 'MADRID',
			 'Sri Lanka': 'SRI JAYAWARDENEPURA KOTTE',
			 'Sudan': 'KHARTOUM',
			 'Suriname': 'PARAMARIBO',
			 'South Sudan': 'JUBA',
			 'Swaziland': 'MBABANE',
			 'Sweden': 'STOCKHOLM',
			 'Switzerland': 'BERN',
			 'Syria': 'DAMASCUS',
			 'Taiwan': 'TAIPEI',
			 'Timor-Leste': 'DILI',
			 'Togo': 'LOME',
			 'Tonga': 'NUKU ALOFA',
			 'Trinidad and Tobago': 'PORT OF SPAIN',
			 'Tunisia': 'TUNIS',
			 'Turkey': 'ANKARA',
			 'Turkmenistan': 'ASHGABAT',
			 'Tuvalu': 'FUNAFUTI',
			 'Uganda': 'KAMPALA',
			 'Ukraine': 'KIEV',
			 'United Arab Emirates': 'ABU DHABI',
			 'United Kingdom': 'LONDON',
			 'United States': 'WASHINGTON DC',
			 'Uruguay': 'MONTEVIDEO',
			 'Uzbekistan': 'TASHKENT',
			 'Vanuatu': 'PORT VILA',
			 'Venezuela': 'CARACAS',
			 'Vietnam': 'HANOI',
			 'Yemen': 'SANAA',
			 'Zambia': 'LUSAKA',
			 'Zimbabwe': 'HARARE'
			 }
		 
			 
			 
